version: '3'
services:
  nginxpm:
    container_name: nginxpm
    image: jc21/nginx-proxy-manager:latest
    ports:
      - 8080:80
      - 8081:81
      - 40443:443
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    restart: unless-stopped
