version: '3'
services:
  guacamole:
    container_name: guacamole
    image: flcontainers/guacamole:latest
    ports:
      - 8180:8080
    volumes:
      - ./config:/config
    restart: unless-stopped
