version: '3'
services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - 59090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 53000:3000
    restart: unless-stopped
