version: '3'
services:
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome
    ports:
      - 5053:53/tcp
      - 5053:53/udp
      - 8180:80/tcp
      - 41443:443/tcp
      - 3100:3000/tcp
    volumes:
      - ./conf:/opt/adguardhome/conf
      - ./work:/opt/adguardhome/work
    restart: unless-stopped
