version: '3'
services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:latest
    ports:
      - 53001:3001
    volumes:
      - ./data:/app/data
    restart: unless-stopped
