version: '3'
services:
  nginxpm:
    container_name: nginxpm
    image: jc21/nginx-proxy-manager:latest
    environment:
      DISABLE_IPV6: 'true'
    ports:
      - 50080:80
      - 50081:81
      - 50443:443
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    restart: unless-stopped
